/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldcupRouteImport } from './routes/worldcup'
import { Route as WelcomeukRouteImport } from './routes/welcomeuk'
import { Route as WelcomejoziRouteImport } from './routes/welcomejozi'
import { Route as WelcomectRouteImport } from './routes/welcomect'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CreatethevibeRouteImport } from './routes/createthevibe'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiIntakeRouteImport } from './routes/api/intake'
import { Route as AuthenticatedMyEventsRouteImport } from './routes/_authenticated/my-events'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiWatchpartyConfigRouteImport } from './routes/api/watchparty/config'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthenticatedEventChatIdRouteImport } from './routes/_authenticated/event-chat.$id'
import { Route as AuthenticatedAdminWorldcupRouteImport } from './routes/_authenticated/admin.worldcup'
import { Route as ApiWatchpartyAdminSummaryRouteImport } from './routes/api/watchparty/admin/summary'
import { Route as ApiWatchpartyAdminSignupsRouteImport } from './routes/api/watchparty/admin/signups'
import { Route as ApiWatchpartyAdminRandomWinnerRouteImport } from './routes/api/watchparty/admin/random-winner'

const WorldcupRoute = WorldcupRouteImport.update({
  id: '/worldcup',
  path: '/worldcup',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeukRoute = WelcomeukRouteImport.update({
  id: '/welcomeuk',
  path: '/welcomeuk',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomejoziRoute = WelcomejoziRouteImport.update({
  id: '/welcomejozi',
  path: '/welcomejozi',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomectRoute = WelcomectRouteImport.update({
  id: '/welcomect',
  path: '/welcomect',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatethevibeRoute = CreatethevibeRouteImport.update({
  id: '/createthevibe',
  path: '/createthevibe',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntakeRoute = ApiIntakeRouteImport.update({
  id: '/api/intake',
  path: '/api/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyEventsRoute = AuthenticatedMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWatchpartyConfigRoute = ApiWatchpartyConfigRouteImport.update({
  id: '/api/watchparty/config',
  path: '/api/watchparty/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMessagesRoute,
} as any)
const AuthenticatedEventChatIdRoute =
  AuthenticatedEventChatIdRouteImport.update({
    id: '/event-chat/$id',
    path: '/event-chat/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorldcupRoute =
  AuthenticatedAdminWorldcupRouteImport.update({
    id: '/worldcup',
    path: '/worldcup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiWatchpartyAdminSummaryRoute =
  ApiWatchpartyAdminSummaryRouteImport.update({
    id: '/api/watchparty/admin/summary',
    path: '/api/watchparty/admin/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWatchpartyAdminSignupsRoute =
  ApiWatchpartyAdminSignupsRouteImport.update({
    id: '/api/watchparty/admin/signups',
    path: '/api/watchparty/admin/signups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWatchpartyAdminRandomWinnerRoute =
  ApiWatchpartyAdminRandomWinnerRouteImport.update({
    id: '/api/watchparty/admin/random-winner',
    path: '/api/watchparty/admin/random-winner',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/createthevibe': typeof CreatethevibeRoute
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/movement': typeof MovementRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/welcomect': typeof WelcomectRoute
  '/welcomejozi': typeof WelcomejoziRoute
  '/welcomeuk': typeof WelcomeukRoute
  '/worldcup': typeof WorldcupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/u/$id': typeof UIdRoute
  '/news/': typeof NewsIndexRoute
  '/admin/worldcup': typeof AuthenticatedAdminWorldcupRoute
  '/event-chat/$id': typeof AuthenticatedEventChatIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/watchparty/config': typeof ApiWatchpartyConfigRoute
  '/api/watchparty/admin/random-winner': typeof ApiWatchpartyAdminRandomWinnerRoute
  '/api/watchparty/admin/signups': typeof ApiWatchpartyAdminSignupsRoute
  '/api/watchparty/admin/summary': typeof ApiWatchpartyAdminSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/createthevibe': typeof CreatethevibeRoute
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/movement': typeof MovementRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/welcomect': typeof WelcomectRoute
  '/welcomejozi': typeof WelcomejoziRoute
  '/welcomeuk': typeof WelcomeukRoute
  '/worldcup': typeof WorldcupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/u/$id': typeof UIdRoute
  '/news': typeof NewsIndexRoute
  '/admin/worldcup': typeof AuthenticatedAdminWorldcupRoute
  '/event-chat/$id': typeof AuthenticatedEventChatIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/watchparty/config': typeof ApiWatchpartyConfigRoute
  '/api/watchparty/admin/random-winner': typeof ApiWatchpartyAdminRandomWinnerRoute
  '/api/watchparty/admin/signups': typeof ApiWatchpartyAdminSignupsRoute
  '/api/watchparty/admin/summary': typeof ApiWatchpartyAdminSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/community': typeof CommunityRoute
  '/createthevibe': typeof CreatethevibeRoute
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/movement': typeof MovementRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/welcomect': typeof WelcomectRoute
  '/welcomejozi': typeof WelcomejoziRoute
  '/welcomeuk': typeof WelcomeukRoute
  '/worldcup': typeof WorldcupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/my-events': typeof AuthenticatedMyEventsRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/u/$id': typeof UIdRoute
  '/news/': typeof NewsIndexRoute
  '/_authenticated/admin/worldcup': typeof AuthenticatedAdminWorldcupRoute
  '/_authenticated/event-chat/$id': typeof AuthenticatedEventChatIdRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/watchparty/config': typeof ApiWatchpartyConfigRoute
  '/api/watchparty/admin/random-winner': typeof ApiWatchpartyAdminRandomWinnerRoute
  '/api/watchparty/admin/signups': typeof ApiWatchpartyAdminSignupsRoute
  '/api/watchparty/admin/summary': typeof ApiWatchpartyAdminSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/createthevibe'
    | '/events'
    | '/groups'
    | '/login'
    | '/membership'
    | '/movement'
    | '/privacy'
    | '/register'
    | '/search'
    | '/signup'
    | '/terms'
    | '/welcomect'
    | '/welcomejozi'
    | '/welcomeuk'
    | '/worldcup'
    | '/account'
    | '/admin'
    | '/messages'
    | '/my-events'
    | '/api/intake'
    | '/api/upload'
    | '/auth/callback'
    | '/events/$id'
    | '/news/$slug'
    | '/u/$id'
    | '/news/'
    | '/admin/worldcup'
    | '/event-chat/$id'
    | '/messages/$id'
    | '/api/stripe/webhook'
    | '/api/watchparty/config'
    | '/api/watchparty/admin/random-winner'
    | '/api/watchparty/admin/signups'
    | '/api/watchparty/admin/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/createthevibe'
    | '/events'
    | '/groups'
    | '/login'
    | '/membership'
    | '/movement'
    | '/privacy'
    | '/register'
    | '/search'
    | '/signup'
    | '/terms'
    | '/welcomect'
    | '/welcomejozi'
    | '/welcomeuk'
    | '/worldcup'
    | '/account'
    | '/admin'
    | '/messages'
    | '/my-events'
    | '/api/intake'
    | '/api/upload'
    | '/auth/callback'
    | '/events/$id'
    | '/news/$slug'
    | '/u/$id'
    | '/news'
    | '/admin/worldcup'
    | '/event-chat/$id'
    | '/messages/$id'
    | '/api/stripe/webhook'
    | '/api/watchparty/config'
    | '/api/watchparty/admin/random-winner'
    | '/api/watchparty/admin/signups'
    | '/api/watchparty/admin/summary'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/community'
    | '/createthevibe'
    | '/events'
    | '/groups'
    | '/login'
    | '/membership'
    | '/movement'
    | '/privacy'
    | '/register'
    | '/search'
    | '/signup'
    | '/terms'
    | '/welcomect'
    | '/welcomejozi'
    | '/welcomeuk'
    | '/worldcup'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/messages'
    | '/_authenticated/my-events'
    | '/api/intake'
    | '/api/upload'
    | '/auth/callback'
    | '/events/$id'
    | '/news/$slug'
    | '/u/$id'
    | '/news/'
    | '/_authenticated/admin/worldcup'
    | '/_authenticated/event-chat/$id'
    | '/_authenticated/messages/$id'
    | '/api/stripe/webhook'
    | '/api/watchparty/config'
    | '/api/watchparty/admin/random-winner'
    | '/api/watchparty/admin/signups'
    | '/api/watchparty/admin/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  CreatethevibeRoute: typeof CreatethevibeRoute
  EventsRoute: typeof EventsRouteWithChildren
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  MovementRoute: typeof MovementRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  WelcomectRoute: typeof WelcomectRoute
  WelcomejoziRoute: typeof WelcomejoziRoute
  WelcomeukRoute: typeof WelcomeukRoute
  WorldcupRoute: typeof WorldcupRoute
  ApiIntakeRoute: typeof ApiIntakeRoute
  ApiUploadRoute: typeof ApiUploadRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  NewsSlugRoute: typeof NewsSlugRoute
  UIdRoute: typeof UIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWatchpartyConfigRoute: typeof ApiWatchpartyConfigRoute
  ApiWatchpartyAdminRandomWinnerRoute: typeof ApiWatchpartyAdminRandomWinnerRoute
  ApiWatchpartyAdminSignupsRoute: typeof ApiWatchpartyAdminSignupsRoute
  ApiWatchpartyAdminSummaryRoute: typeof ApiWatchpartyAdminSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worldcup': {
      id: '/worldcup'
      path: '/worldcup'
      fullPath: '/worldcup'
      preLoaderRoute: typeof WorldcupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcomeuk': {
      id: '/welcomeuk'
      path: '/welcomeuk'
      fullPath: '/welcomeuk'
      preLoaderRoute: typeof WelcomeukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcomejozi': {
      id: '/welcomejozi'
      path: '/welcomejozi'
      fullPath: '/welcomejozi'
      preLoaderRoute: typeof WelcomejoziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcomect': {
      id: '/welcomect'
      path: '/welcomect'
      fullPath: '/welcomect'
      preLoaderRoute: typeof WelcomectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createthevibe': {
      id: '/createthevibe'
      path: '/createthevibe'
      fullPath: '/createthevibe'
      preLoaderRoute: typeof CreatethevibeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intake': {
      id: '/api/intake'
      path: '/api/intake'
      fullPath: '/api/intake'
      preLoaderRoute: typeof ApiIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-events': {
      id: '/_authenticated/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof AuthenticatedMyEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/watchparty/config': {
      id: '/api/watchparty/config'
      path: '/api/watchparty/config'
      fullPath: '/api/watchparty/config'
      preLoaderRoute: typeof ApiWatchpartyConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/event-chat/$id': {
      id: '/_authenticated/event-chat/$id'
      path: '/event-chat/$id'
      fullPath: '/event-chat/$id'
      preLoaderRoute: typeof AuthenticatedEventChatIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/worldcup': {
      id: '/_authenticated/admin/worldcup'
      path: '/worldcup'
      fullPath: '/admin/worldcup'
      preLoaderRoute: typeof AuthenticatedAdminWorldcupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/watchparty/admin/summary': {
      id: '/api/watchparty/admin/summary'
      path: '/api/watchparty/admin/summary'
      fullPath: '/api/watchparty/admin/summary'
      preLoaderRoute: typeof ApiWatchpartyAdminSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchparty/admin/signups': {
      id: '/api/watchparty/admin/signups'
      path: '/api/watchparty/admin/signups'
      fullPath: '/api/watchparty/admin/signups'
      preLoaderRoute: typeof ApiWatchpartyAdminSignupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchparty/admin/random-winner': {
      id: '/api/watchparty/admin/random-winner'
      path: '/api/watchparty/admin/random-winner'
      fullPath: '/api/watchparty/admin/random-winner'
      preLoaderRoute: typeof ApiWatchpartyAdminRandomWinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminWorldcupRoute: typeof AuthenticatedAdminWorldcupRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminWorldcupRoute: AuthenticatedAdminWorldcupRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedMyEventsRoute: typeof AuthenticatedMyEventsRoute
  AuthenticatedEventChatIdRoute: typeof AuthenticatedEventChatIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedMyEventsRoute: AuthenticatedMyEventsRoute,
  AuthenticatedEventChatIdRoute: AuthenticatedEventChatIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CommunityRoute: CommunityRoute,
  CreatethevibeRoute: CreatethevibeRoute,
  EventsRoute: EventsRouteWithChildren,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  MovementRoute: MovementRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  WelcomectRoute: WelcomectRoute,
  WelcomejoziRoute: WelcomejoziRoute,
  WelcomeukRoute: WelcomeukRoute,
  WorldcupRoute: WorldcupRoute,
  ApiIntakeRoute: ApiIntakeRoute,
  ApiUploadRoute: ApiUploadRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  NewsSlugRoute: NewsSlugRoute,
  UIdRoute: UIdRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWatchpartyConfigRoute: ApiWatchpartyConfigRoute,
  ApiWatchpartyAdminRandomWinnerRoute: ApiWatchpartyAdminRandomWinnerRoute,
  ApiWatchpartyAdminSignupsRoute: ApiWatchpartyAdminSignupsRoute,
  ApiWatchpartyAdminSummaryRoute: ApiWatchpartyAdminSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
